create table cara_Join (
	jobId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	projectId LONG,
	jobType VARCHAR(75) null,
	variant VARCHAR(75) null,
	format VARCHAR(75) null,
	visualDesign BOOLEAN,
	visualDesignCu BOOLEAN,
	noticableConsumers BOOLEAN,
	changePackaging BOOLEAN,
	changeFormulation BOOLEAN,
	visualDesignComplete DATE null,
	artworkApproved DATE null,
	separationFilesToPrinter DATE null,
	marketDeployment DATE null,
	shipToTrade DATE null,
	designAgency LONG,
	pmaUser LONG,
	localMarketing LONG,
	rndLocalDeployUser LONG,
	projectName VARCHAR(75) null,
	projectCategory VARCHAR(75) null,
	projectType VARCHAR(75) null,
	brand VARCHAR(75) null,
	projectUserId LONG
);