/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.unilever.demo.cara.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the project service. Represents a row in the &quot;Cara_project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.unilever.demo.cara.model.impl.projectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.unilever.demo.cara.model.impl.projectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see project
 * @see com.liferay.unilever.demo.cara.model.impl.projectImpl
 * @see com.liferay.unilever.demo.cara.model.impl.projectModelImpl
 * @generated
 */
@ProviderType
public interface projectModel extends BaseModel<project>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project.
	 *
	 * @return the uuid of this project
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project.
	 *
	 * @param uuid the uuid of this project
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the group ID of this project.
	 *
	 * @return the group ID of this project
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project.
	 *
	 * @param groupId the group ID of this project
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project.
	 *
	 * @return the user ID of this project
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project.
	 *
	 * @param userId the user ID of this project
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project.
	 *
	 * @return the user uuid of this project
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project.
	 *
	 * @param userUuid the user uuid of this project
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project.
	 *
	 * @return the user name of this project
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project.
	 *
	 * @param userName the user name of this project
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this project.
	 *
	 * @return the status of this project
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this project.
	 *
	 * @param status the status of this project
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this project.
	 *
	 * @return the status by user ID of this project
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this project.
	 *
	 * @param statusByUserId the status by user ID of this project
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this project.
	 *
	 * @return the status by user uuid of this project
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this project.
	 *
	 * @param statusByUserUuid the status by user uuid of this project
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this project.
	 *
	 * @return the status by user name of this project
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this project.
	 *
	 * @param statusByUserName the status by user name of this project
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this project.
	 *
	 * @return the status date of this project
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this project.
	 *
	 * @param statusDate the status date of this project
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the project ref ID of this project.
	 *
	 * @return the project ref ID of this project
	 */
	@AutoEscape
	public String getProjectRefId();

	/**
	 * Sets the project ref ID of this project.
	 *
	 * @param projectRefId the project ref ID of this project
	 */
	public void setProjectRefId(String projectRefId);

	/**
	 * Returns the project name of this project.
	 *
	 * @return the project name of this project
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this project.
	 *
	 * @param projectName the project name of this project
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the project type of this project.
	 *
	 * @return the project type of this project
	 */
	@AutoEscape
	public String getProjectType();

	/**
	 * Sets the project type of this project.
	 *
	 * @param projectType the project type of this project
	 */
	public void setProjectType(String projectType);

	/**
	 * Returns the brand of this project.
	 *
	 * @return the brand of this project
	 */
	@AutoEscape
	public String getBrand();

	/**
	 * Sets the brand of this project.
	 *
	 * @param brand the brand of this project
	 */
	public void setBrand(String brand);

	/**
	 * Returns the brand position of this project.
	 *
	 * @return the brand position of this project
	 */
	@AutoEscape
	public String getBrandPosition();

	/**
	 * Sets the brand position of this project.
	 *
	 * @param brandPosition the brand position of this project
	 */
	public void setBrandPosition(String brandPosition);

	/**
	 * Returns the project category of this project.
	 *
	 * @return the project category of this project
	 */
	@AutoEscape
	public String getProjectCategory();

	/**
	 * Sets the project category of this project.
	 *
	 * @param projectCategory the project category of this project
	 */
	public void setProjectCategory(String projectCategory);

	/**
	 * Returns the charter gate approval of this project.
	 *
	 * @return the charter gate approval of this project
	 */
	public Date getCharterGateApproval();

	/**
	 * Sets the charter gate approval of this project.
	 *
	 * @param charterGateApproval the charter gate approval of this project
	 */
	public void setCharterGateApproval(Date charterGateApproval);

	/**
	 * Returns the product design lock of this project.
	 *
	 * @return the product design lock of this project
	 */
	public Date getProductDesignLock();

	/**
	 * Sets the product design lock of this project.
	 *
	 * @param productDesignLock the product design lock of this project
	 */
	public void setProductDesignLock(Date productDesignLock);

	/**
	 * Returns the contract gate approval of this project.
	 *
	 * @return the contract gate approval of this project
	 */
	public Date getContractGateApproval();

	/**
	 * Sets the contract gate approval of this project.
	 *
	 * @param contractGateApproval the contract gate approval of this project
	 */
	public void setContractGateApproval(Date contractGateApproval);

	/**
	 * Returns the market ready approval of this project.
	 *
	 * @return the market ready approval of this project
	 */
	public Date getMarketReadyApproval();

	/**
	 * Sets the market ready approval of this project.
	 *
	 * @param marketReadyApproval the market ready approval of this project
	 */
	public void setMarketReadyApproval(Date marketReadyApproval);

	/**
	 * Returns the market deployment of this project.
	 *
	 * @return the market deployment of this project
	 */
	public Date getMarketDeployment();

	/**
	 * Sets the market deployment of this project.
	 *
	 * @param marketDeployment the market deployment of this project
	 */
	public void setMarketDeployment(Date marketDeployment);

	/**
	 * Returns the ship to trade of this project.
	 *
	 * @return the ship to trade of this project
	 */
	public Date getShipToTrade();

	/**
	 * Sets the ship to trade of this project.
	 *
	 * @param shipToTrade the ship to trade of this project
	 */
	public void setShipToTrade(Date shipToTrade);

	/**
	 * Returns the marketing user ID of this project.
	 *
	 * @return the marketing user ID of this project
	 */
	public long getMarketingUserId();

	/**
	 * Sets the marketing user ID of this project.
	 *
	 * @param marketingUserId the marketing user ID of this project
	 */
	public void setMarketingUserId(long marketingUserId);

	/**
	 * Returns the marketing user uuid of this project.
	 *
	 * @return the marketing user uuid of this project
	 */
	public String getMarketingUserUuid();

	/**
	 * Sets the marketing user uuid of this project.
	 *
	 * @param marketingUserUuid the marketing user uuid of this project
	 */
	public void setMarketingUserUuid(String marketingUserUuid);

	/**
	 * Returns the rnd user ID of this project.
	 *
	 * @return the rnd user ID of this project
	 */
	public long getRndUserId();

	/**
	 * Sets the rnd user ID of this project.
	 *
	 * @param rndUserId the rnd user ID of this project
	 */
	public void setRndUserId(long rndUserId);

	/**
	 * Returns the rnd user uuid of this project.
	 *
	 * @return the rnd user uuid of this project
	 */
	public String getRndUserUuid();

	/**
	 * Sets the rnd user uuid of this project.
	 *
	 * @param rndUserUuid the rnd user uuid of this project
	 */
	public void setRndUserUuid(String rndUserUuid);

	/**
	 * Returns the rnd product user ID of this project.
	 *
	 * @return the rnd product user ID of this project
	 */
	public long getRndProductUserId();

	/**
	 * Sets the rnd product user ID of this project.
	 *
	 * @param rndProductUserId the rnd product user ID of this project
	 */
	public void setRndProductUserId(long rndProductUserId);

	/**
	 * Returns the rnd product user uuid of this project.
	 *
	 * @return the rnd product user uuid of this project
	 */
	public String getRndProductUserUuid();

	/**
	 * Sets the rnd product user uuid of this project.
	 *
	 * @param rndProductUserUuid the rnd product user uuid of this project
	 */
	public void setRndProductUserUuid(String rndProductUserUuid);

	/**
	 * Returns the supply chain user ID of this project.
	 *
	 * @return the supply chain user ID of this project
	 */
	public long getSupplyChainUserId();

	/**
	 * Sets the supply chain user ID of this project.
	 *
	 * @param supplyChainUserId the supply chain user ID of this project
	 */
	public void setSupplyChainUserId(long supplyChainUserId);

	/**
	 * Returns the supply chain user uuid of this project.
	 *
	 * @return the supply chain user uuid of this project
	 */
	public String getSupplyChainUserUuid();

	/**
	 * Sets the supply chain user uuid of this project.
	 *
	 * @param supplyChainUserUuid the supply chain user uuid of this project
	 */
	public void setSupplyChainUserUuid(String supplyChainUserUuid);

	/**
	 * Returns the customer development user ID of this project.
	 *
	 * @return the customer development user ID of this project
	 */
	public long getCustomerDevelopmentUserId();

	/**
	 * Sets the customer development user ID of this project.
	 *
	 * @param customerDevelopmentUserId the customer development user ID of this project
	 */
	public void setCustomerDevelopmentUserId(long customerDevelopmentUserId);

	/**
	 * Returns the customer development user uuid of this project.
	 *
	 * @return the customer development user uuid of this project
	 */
	public String getCustomerDevelopmentUserUuid();

	/**
	 * Sets the customer development user uuid of this project.
	 *
	 * @param customerDevelopmentUserUuid the customer development user uuid of this project
	 */
	public void setCustomerDevelopmentUserUuid(
		String customerDevelopmentUserUuid);

	/**
	 * Returns the tech leader user ID of this project.
	 *
	 * @return the tech leader user ID of this project
	 */
	public long getTechLeaderUserId();

	/**
	 * Sets the tech leader user ID of this project.
	 *
	 * @param techLeaderUserId the tech leader user ID of this project
	 */
	public void setTechLeaderUserId(long techLeaderUserId);

	/**
	 * Returns the tech leader user uuid of this project.
	 *
	 * @return the tech leader user uuid of this project
	 */
	public String getTechLeaderUserUuid();

	/**
	 * Sets the tech leader user uuid of this project.
	 *
	 * @param techLeaderUserUuid the tech leader user uuid of this project
	 */
	public void setTechLeaderUserUuid(String techLeaderUserUuid);

	/**
	 * Returns <code>true</code> if this project is approved.
	 *
	 * @return <code>true</code> if this project is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this project is denied.
	 *
	 * @return <code>true</code> if this project is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this project is a draft.
	 *
	 * @return <code>true</code> if this project is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this project is expired.
	 *
	 * @return <code>true</code> if this project is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this project is inactive.
	 *
	 * @return <code>true</code> if this project is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this project is incomplete.
	 *
	 * @return <code>true</code> if this project is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this project is pending.
	 *
	 * @return <code>true</code> if this project is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this project is scheduled.
	 *
	 * @return <code>true</code> if this project is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.unilever.demo.cara.model.project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.unilever.demo.cara.model.project> toCacheModel();

	@Override
	public com.liferay.unilever.demo.cara.model.project toEscapedModel();

	@Override
	public com.liferay.unilever.demo.cara.model.project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}