/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.unilever.demo.cara.join.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Join service. Represents a row in the &quot;cara_Join&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.unilever.demo.cara.join.model.impl.JoinModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.unilever.demo.cara.join.model.impl.JoinImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Join
 * @see com.liferay.unilever.demo.cara.join.model.impl.JoinImpl
 * @see com.liferay.unilever.demo.cara.join.model.impl.JoinModelImpl
 * @generated
 */
@ProviderType
public interface JoinModel extends BaseModel<Join>, GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a join model instance should use the {@link Join} interface instead.
	 */

	/**
	 * Returns the primary key of this join.
	 *
	 * @return the primary key of this join
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this join.
	 *
	 * @param primaryKey the primary key of this join
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this join.
	 *
	 * @return the job ID of this join
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this join.
	 *
	 * @param jobId the job ID of this join
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the group ID of this join.
	 *
	 * @return the group ID of this join
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this join.
	 *
	 * @param groupId the group ID of this join
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this join.
	 *
	 * @return the company ID of this join
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this join.
	 *
	 * @param companyId the company ID of this join
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this join.
	 *
	 * @return the user ID of this join
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this join.
	 *
	 * @param userId the user ID of this join
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this join.
	 *
	 * @return the user uuid of this join
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this join.
	 *
	 * @param userUuid the user uuid of this join
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this join.
	 *
	 * @return the user name of this join
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this join.
	 *
	 * @param userName the user name of this join
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this join.
	 *
	 * @return the create date of this join
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this join.
	 *
	 * @param createDate the create date of this join
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this join.
	 *
	 * @return the modified date of this join
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this join.
	 *
	 * @param modifiedDate the modified date of this join
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project ID of this join.
	 *
	 * @return the project ID of this join
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this join.
	 *
	 * @param projectId the project ID of this join
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the job type of this join.
	 *
	 * @return the job type of this join
	 */
	@AutoEscape
	public String getJobType();

	/**
	 * Sets the job type of this join.
	 *
	 * @param jobType the job type of this join
	 */
	public void setJobType(String jobType);

	/**
	 * Returns the variant of this join.
	 *
	 * @return the variant of this join
	 */
	@AutoEscape
	public String getVariant();

	/**
	 * Sets the variant of this join.
	 *
	 * @param variant the variant of this join
	 */
	public void setVariant(String variant);

	/**
	 * Returns the format of this join.
	 *
	 * @return the format of this join
	 */
	@AutoEscape
	public String getFormat();

	/**
	 * Sets the format of this join.
	 *
	 * @param format the format of this join
	 */
	public void setFormat(String format);

	/**
	 * Returns the visual design of this join.
	 *
	 * @return the visual design of this join
	 */
	public Boolean getVisualDesign();

	/**
	 * Sets the visual design of this join.
	 *
	 * @param visualDesign the visual design of this join
	 */
	public void setVisualDesign(Boolean visualDesign);

	/**
	 * Returns the visual design cu of this join.
	 *
	 * @return the visual design cu of this join
	 */
	public Boolean getVisualDesignCu();

	/**
	 * Sets the visual design cu of this join.
	 *
	 * @param visualDesignCu the visual design cu of this join
	 */
	public void setVisualDesignCu(Boolean visualDesignCu);

	/**
	 * Returns the noticable consumers of this join.
	 *
	 * @return the noticable consumers of this join
	 */
	public Boolean getNoticableConsumers();

	/**
	 * Sets the noticable consumers of this join.
	 *
	 * @param noticableConsumers the noticable consumers of this join
	 */
	public void setNoticableConsumers(Boolean noticableConsumers);

	/**
	 * Returns the change packaging of this join.
	 *
	 * @return the change packaging of this join
	 */
	public Boolean getChangePackaging();

	/**
	 * Sets the change packaging of this join.
	 *
	 * @param changePackaging the change packaging of this join
	 */
	public void setChangePackaging(Boolean changePackaging);

	/**
	 * Returns the change formulation of this join.
	 *
	 * @return the change formulation of this join
	 */
	public Boolean getChangeFormulation();

	/**
	 * Sets the change formulation of this join.
	 *
	 * @param changeFormulation the change formulation of this join
	 */
	public void setChangeFormulation(Boolean changeFormulation);

	/**
	 * Returns the visual design complete of this join.
	 *
	 * @return the visual design complete of this join
	 */
	public Date getVisualDesignComplete();

	/**
	 * Sets the visual design complete of this join.
	 *
	 * @param visualDesignComplete the visual design complete of this join
	 */
	public void setVisualDesignComplete(Date visualDesignComplete);

	/**
	 * Returns the artwork approved of this join.
	 *
	 * @return the artwork approved of this join
	 */
	public Date getArtworkApproved();

	/**
	 * Sets the artwork approved of this join.
	 *
	 * @param artworkApproved the artwork approved of this join
	 */
	public void setArtworkApproved(Date artworkApproved);

	/**
	 * Returns the separation files to printer of this join.
	 *
	 * @return the separation files to printer of this join
	 */
	public Date getSeparationFilesToPrinter();

	/**
	 * Sets the separation files to printer of this join.
	 *
	 * @param separationFilesToPrinter the separation files to printer of this join
	 */
	public void setSeparationFilesToPrinter(Date separationFilesToPrinter);

	/**
	 * Returns the market deployment of this join.
	 *
	 * @return the market deployment of this join
	 */
	public Date getMarketDeployment();

	/**
	 * Sets the market deployment of this join.
	 *
	 * @param marketDeployment the market deployment of this join
	 */
	public void setMarketDeployment(Date marketDeployment);

	/**
	 * Returns the ship to trade of this join.
	 *
	 * @return the ship to trade of this join
	 */
	public Date getShipToTrade();

	/**
	 * Sets the ship to trade of this join.
	 *
	 * @param shipToTrade the ship to trade of this join
	 */
	public void setShipToTrade(Date shipToTrade);

	/**
	 * Returns the design agency of this join.
	 *
	 * @return the design agency of this join
	 */
	public long getDesignAgency();

	/**
	 * Sets the design agency of this join.
	 *
	 * @param designAgency the design agency of this join
	 */
	public void setDesignAgency(long designAgency);

	/**
	 * Returns the pma user of this join.
	 *
	 * @return the pma user of this join
	 */
	public long getPmaUser();

	/**
	 * Sets the pma user of this join.
	 *
	 * @param pmaUser the pma user of this join
	 */
	public void setPmaUser(long pmaUser);

	/**
	 * Returns the local marketing of this join.
	 *
	 * @return the local marketing of this join
	 */
	public long getLocalMarketing();

	/**
	 * Sets the local marketing of this join.
	 *
	 * @param localMarketing the local marketing of this join
	 */
	public void setLocalMarketing(long localMarketing);

	/**
	 * Returns the rnd local deploy user of this join.
	 *
	 * @return the rnd local deploy user of this join
	 */
	public long getRndLocalDeployUser();

	/**
	 * Sets the rnd local deploy user of this join.
	 *
	 * @param rndLocalDeployUser the rnd local deploy user of this join
	 */
	public void setRndLocalDeployUser(long rndLocalDeployUser);

	/**
	 * Returns the project name of this join.
	 *
	 * @return the project name of this join
	 */
	@AutoEscape
	public String getProjectName();

	/**
	 * Sets the project name of this join.
	 *
	 * @param projectName the project name of this join
	 */
	public void setProjectName(String projectName);

	/**
	 * Returns the project category of this join.
	 *
	 * @return the project category of this join
	 */
	@AutoEscape
	public String getProjectCategory();

	/**
	 * Sets the project category of this join.
	 *
	 * @param projectCategory the project category of this join
	 */
	public void setProjectCategory(String projectCategory);

	/**
	 * Returns the project type of this join.
	 *
	 * @return the project type of this join
	 */
	@AutoEscape
	public String getProjectType();

	/**
	 * Sets the project type of this join.
	 *
	 * @param projectType the project type of this join
	 */
	public void setProjectType(String projectType);

	/**
	 * Returns the brand of this join.
	 *
	 * @return the brand of this join
	 */
	@AutoEscape
	public String getBrand();

	/**
	 * Sets the brand of this join.
	 *
	 * @param brand the brand of this join
	 */
	public void setBrand(String brand);

	/**
	 * Returns the project user ID of this join.
	 *
	 * @return the project user ID of this join
	 */
	public long getProjectUserId();

	/**
	 * Sets the project user ID of this join.
	 *
	 * @param projectUserId the project user ID of this join
	 */
	public void setProjectUserId(long projectUserId);

	/**
	 * Returns the project user uuid of this join.
	 *
	 * @return the project user uuid of this join
	 */
	public String getProjectUserUuid();

	/**
	 * Sets the project user uuid of this join.
	 *
	 * @param projectUserUuid the project user uuid of this join
	 */
	public void setProjectUserUuid(String projectUserUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Join join);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Join> toCacheModel();

	@Override
	public Join toEscapedModel();

	@Override
	public Join toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}