/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.unilever.demo.cara.taskdetails.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaskDetails service. Represents a row in the &quot;Cara_TaskDetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.unilever.demo.cara.taskdetails.model.impl.TaskDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.unilever.demo.cara.taskdetails.model.impl.TaskDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskDetails
 * @see com.liferay.unilever.demo.cara.taskdetails.model.impl.TaskDetailsImpl
 * @see com.liferay.unilever.demo.cara.taskdetails.model.impl.TaskDetailsModelImpl
 * @generated
 */
@ProviderType
public interface TaskDetailsModel extends BaseModel<TaskDetails>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task details model instance should use the {@link TaskDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this task details.
	 *
	 * @return the primary key of this task details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task details.
	 *
	 * @param primaryKey the primary key of this task details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task details.
	 *
	 * @return the uuid of this task details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task details.
	 *
	 * @param uuid the uuid of this task details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task details ID of this task details.
	 *
	 * @return the task details ID of this task details
	 */
	public long getTaskDetailsId();

	/**
	 * Sets the task details ID of this task details.
	 *
	 * @param taskDetailsId the task details ID of this task details
	 */
	public void setTaskDetailsId(long taskDetailsId);

	/**
	 * Returns the group ID of this task details.
	 *
	 * @return the group ID of this task details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task details.
	 *
	 * @param groupId the group ID of this task details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task details.
	 *
	 * @return the company ID of this task details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task details.
	 *
	 * @param companyId the company ID of this task details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task details.
	 *
	 * @return the user ID of this task details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task details.
	 *
	 * @param userId the user ID of this task details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task details.
	 *
	 * @return the user uuid of this task details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this task details.
	 *
	 * @param userUuid the user uuid of this task details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task details.
	 *
	 * @return the user name of this task details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task details.
	 *
	 * @param userName the user name of this task details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task details.
	 *
	 * @return the create date of this task details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task details.
	 *
	 * @param createDate the create date of this task details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task details.
	 *
	 * @return the modified date of this task details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task details.
	 *
	 * @param modifiedDate the modified date of this task details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the job ID of this task details.
	 *
	 * @return the job ID of this task details
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this task details.
	 *
	 * @param jobId the job ID of this task details
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the task ID of this task details.
	 *
	 * @return the task ID of this task details
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task details.
	 *
	 * @param taskId the task ID of this task details
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the file url of this task details.
	 *
	 * @return the file url of this task details
	 */
	@AutoEscape
	public String getFileUrl();

	/**
	 * Sets the file url of this task details.
	 *
	 * @param fileUrl the file url of this task details
	 */
	public void setFileUrl(String fileUrl);

	/**
	 * Returns the file ID of this task details.
	 *
	 * @return the file ID of this task details
	 */
	public long getFileId();

	/**
	 * Sets the file ID of this task details.
	 *
	 * @param fileId the file ID of this task details
	 */
	public void setFileId(long fileId);

	/**
	 * Returns the product details of this task details.
	 *
	 * @return the product details of this task details
	 */
	@AutoEscape
	public String getProductDetails();

	/**
	 * Sets the product details of this task details.
	 *
	 * @param productDetails the product details of this task details
	 */
	public void setProductDetails(String productDetails);

	/**
	 * Returns the why use of this task details.
	 *
	 * @return the why use of this task details
	 */
	@AutoEscape
	public String getWhyUse();

	/**
	 * Sets the why use of this task details.
	 *
	 * @param whyUse the why use of this task details
	 */
	public void setWhyUse(String whyUse);

	/**
	 * Returns the how to use of this task details.
	 *
	 * @return the how to use of this task details
	 */
	@AutoEscape
	public String getHowToUse();

	/**
	 * Sets the how to use of this task details.
	 *
	 * @param howToUse the how to use of this task details
	 */
	public void setHowToUse(String howToUse);

	/**
	 * Returns the how it works of this task details.
	 *
	 * @return the how it works of this task details
	 */
	@AutoEscape
	public String getHowItWorks();

	/**
	 * Sets the how it works of this task details.
	 *
	 * @param howItWorks the how it works of this task details
	 */
	public void setHowItWorks(String howItWorks);

	/**
	 * Returns the expert tips of this task details.
	 *
	 * @return the expert tips of this task details
	 */
	@AutoEscape
	public String getExpertTips();

	/**
	 * Sets the expert tips of this task details.
	 *
	 * @param expertTips the expert tips of this task details
	 */
	public void setExpertTips(String expertTips);

	/**
	 * Returns the approved by of this task details.
	 *
	 * @return the approved by of this task details
	 */
	public long getApprovedBy();

	/**
	 * Sets the approved by of this task details.
	 *
	 * @param approvedBy the approved by of this task details
	 */
	public void setApprovedBy(long approvedBy);

	/**
	 * Returns the approved of this task details.
	 *
	 * @return the approved of this task details
	 */
	public Boolean getApproved();

	/**
	 * Sets the approved of this task details.
	 *
	 * @param approved the approved of this task details
	 */
	public void setApproved(Boolean approved);

	/**
	 * Returns the comments of this task details.
	 *
	 * @return the comments of this task details
	 */
	@AutoEscape
	public String getComments();

	/**
	 * Sets the comments of this task details.
	 *
	 * @param comments the comments of this task details
	 */
	public void setComments(String comments);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaskDetails taskDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaskDetails> toCacheModel();

	@Override
	public TaskDetails toEscapedModel();

	@Override
	public TaskDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}